name: mamak_app
description: A new Flutter project.
version: 1.0.0+1
environment: 
  sdk: '>=3.2.0 <4.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  flutter_bloc: ^8.1.3
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.0
  flutter_svg: ^2.0.9
  equatable: ^2.0.5
  google_maps_flutter: ^2.5.0
  smooth_page_indicator: ^1.1.0
  dio: ^5.4.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
flutter: 
  uses-material-design: true
  assets: 
    - assets/
    - assets/images/
  fonts: 
    - family: Inter
      fonts: 
        - asset: assets/fonts/InterBold.ttf
          weight: 700
        - asset: assets/fonts/InterMedium.ttf
          weight: 500
        - asset: assets/fonts/InterSemiBold.ttf
          weight: 600
        - asset: assets/fonts/InterRegular.ttf
          weight: 400
