// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBwLIG0dJ6XhR-qewnw1DOPDxkT4GuO_bQ',
    appId: '1:146062484236:web:88c33e2eef0dba33615f29',
    messagingSenderId: '146062484236',
    projectId: 'flutternight-transportation',
    authDomain: 'flutternight-transportation.firebaseapp.com',
    storageBucket: 'flutternight-transportation.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByssjO2ul-KTKF9w7HBP05hPwvitcc_gA',
    appId: '1:146062484236:android:724114ca575b7822615f29',
    messagingSenderId: '146062484236',
    projectId: 'flutternight-transportation',
    storageBucket: 'flutternight-transportation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMwxfxjOWJFYWspMMXcNqIRI-6AW3Ntpw',
    appId: '1:146062484236:ios:ab926855df5afe44615f29',
    messagingSenderId: '146062484236',
    projectId: 'flutternight-transportation',
    storageBucket: 'flutternight-transportation.appspot.com',
    iosBundleId: 'com.example.transportationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMwxfxjOWJFYWspMMXcNqIRI-6AW3Ntpw',
    appId: '1:146062484236:ios:0764f9933781cbde615f29',
    messagingSenderId: '146062484236',
    projectId: 'flutternight-transportation',
    storageBucket: 'flutternight-transportation.appspot.com',
    iosBundleId: 'com.example.transportationApp.RunnerTests',
  );
}
